# Generated by Django 5.2.7 on 2025-11-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('cantidad_compras', models.IntegerField()),
                ('tipo_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
