# Generated by Django 5.2.7 on 2025-11-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('costo', models.FloatField()),
                ('utilidad', models.FloatField()),
                ('stock', models.IntegerField()),
                ('vendidos', models.IntegerField()),
                ('tendencias', models.CharField(choices=[('alta', 'alta'), ('media', 'media'), ('baja', 'baja')], help_text='Tendencia del producto', max_length=15)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('bajo', 'Bajo en stock'), ('agotado', 'Agotado')], default='disponible', help_text='Estado del producto', max_length=20)),
            ],
        ),
    ]
