# Generated by Django 5.2.7 on 2025-11-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
