# Generated by Django 5.2.7 on 2025-11-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('algoritmo', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confianza_global', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AlterField(
            model_name='ventas',
            name='metodo_compra',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('pago_movil', 'Pago móvil'), ('transferencia', 'Transferencia')], max_length=30),
        ),
        migrations.CreateModel(
            name='EntradaPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('demanda', 'Demanda'), ('tendencia', 'Tendencia'), ('estacionalidad', 'Estacionalidad'), ('categoria', 'Desempeño por categoría'), ('abandono', 'Predicción de abandono'), ('optimizacion_precios', 'Optimización de precios'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('etiqueta_periodo', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=200)),
                ('segmento', models.CharField(blank=True, max_length=200)),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('valor_predicho', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('confianza', models.IntegerField(blank=True, help_text='Confianza en % (0-100)', null=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predicciones', to='Dashboard.productos')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='Dashboard.modeloprediccion')),
            ],
            options={
                'ordering': ['-periodo_inicio', '-creado_en'],
            },
        ),
    ]
