# Generated by Django 5.2.7 on 2025-11-24 00:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_modeloprediccion_alter_ventas_metodo_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad de la recomendación', max_length=10)),
                ('impacto', models.CharField(blank=True, help_text='Impacto estimado (opcional)', max_length=200)),
                ('metadatos', models.JSONField(blank=True, help_text='Campos adicionales/metadata generada por la IA', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recomendaciones_ia', to='Dashboard.productos')),
            ],
            options={
                'verbose_name': 'Recomendación IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
