# Generated by Django 5.2.7 on 2025-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_recomendacionia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('vip', 'VIP'), ('nuevo', 'Nuevo'), ('frecuente', 'Frecuente')], default='nuevo', max_length=20),
        ),
    ]
