# Generated by Django 5.2.7 on 2025-11-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_tasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='display_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
