# Generated by Django 5.2.7 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_add_store_and_selected_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(blank=True, default='md', max_length=8),
        ),
    ]
