# Generated by Django 5.2.7 on 2026-02-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0017_alter_store_id'),
        ('Dashboard', '0017_userprofile_font_size'),
    ]

    operations = []
