"""
Django settings for Django_modules project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde Backend/.env
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-&$8#ob5t5ky3^rlc$1@kryjz@40jzbqz#qn+0w_=7b+)zl)pjy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'Dashboard.apps.DashboardConfig',
    'rest_framework',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Middleware que asigna alias de DB según el prefijo de la URL (/api2/, /api3/)
    'Dashboard.db_router.RequestDBRouterMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_modules.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_modules.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.postgresql",

        "NAME": "trabajo_de_grado",

        "USER": "postgres",

        "PASSWORD": "45220220",

        "HOST": "localhost",

        "PORT": "5432",

    }

}

# Bases de datos adicionales para tiendas/almacenes separadas (usar variables de entorno
# o crear localmente las bases con estos nombres). Cambia los nombres/credenciales si
# tus DB reales difieren.
DATABASES['store_b'] = {
    'ENGINE': 'django.db.backends.postgresql',
    # Ya existen localmente: trabajo_de_grado_store2
    'NAME': os.environ.get('DB_STORE_B_NAME', 'trabajo_de_grado_store2'),
    'USER': os.environ.get('DB_STORE_B_USER', DATABASES['default']['USER']),
    'PASSWORD': os.environ.get('DB_STORE_B_PASSWORD', DATABASES['default']['PASSWORD']),
    'HOST': os.environ.get('DB_STORE_B_HOST', DATABASES['default']['HOST']),
    'PORT': os.environ.get('DB_STORE_B_PORT', DATABASES['default']['PORT']),
}

DATABASES['store_c'] = {
    'ENGINE': 'django.db.backends.postgresql',
    # Ya existen localmente: trabajo_de_grado_store3
    'NAME': os.environ.get('DB_STORE_C_NAME', 'trabajo_de_grado_store3'),
    'USER': os.environ.get('DB_STORE_C_USER', DATABASES['default']['USER']),
    'PASSWORD': os.environ.get('DB_STORE_C_PASSWORD', DATABASES['default']['PASSWORD']),
    'HOST': os.environ.get('DB_STORE_C_HOST', DATABASES['default']['HOST']),
    'PORT': os.environ.get('DB_STORE_C_PORT', DATABASES['default']['PORT']),
}

# Router y middleware para enrutar peticiones por prefijo de URL a DBs separadas
DATABASE_ROUTERS = [
    'Dashboard.db_router.PathRouter',
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ve'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración para REST framework y Simple JWT
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# CORS - durante desarrollo permitir el frontend local
CORS_ALLOW_ALL_ORIGINS = True
# Alternativamente especifica orígenes:
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:5173',
# ]
